name: CI

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
    paths: [
      '.github/workflows/build.yml',
      '.github/workflows/build-linux-cross.yml',
      '.github/workflows/build-cmake-pkg.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp',
      '**/*.cu',
      '**/*.cuh',
      '**/*.swift',
      '**/*.m',
      '**/*.metal',
      '**/*.comp',
      '**/*.glsl'
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_LOG_COLORS: 1
  LLAMA_LOG_PREFIX: 1
  LLAMA_LOG_TIMESTAMPS: 1

jobs:
  ubuntu-cmake-cuda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ver: 'ubuntu24.04'
            cuda: '12.8.1'
            build: '24.04-x64'
            architectures: '50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90-real;120-real'
          - ver: 'ubuntu22.04'
            cuda: '12.8.1'
            build: '22.04-x64'
            architectures: '50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90-real;120-real'
          - ver: 'ubuntu20.04'
            cuda: '12.8.1'
            build: '20.04-x64'
            architectures: '50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90-real;120-real'

    container: nvidia/cuda:${{ matrix.cuda }}-devel-${{ matrix.ver }}

    steps:
        - name: Install dependencies
          env:
            DEBIAN_FRONTEND: noninteractive
          run: |
              apt update
              apt install -y cmake build-essential ninja-build libgomp1 git libssl-dev zip

        - name: Clone
          id: checkout
          uses: actions/checkout@v4

        - name: Fixup git checkout
          run: |
            git config --global --add safe.directory $(pwd)
            git rev-parse

        - name: ccache
          uses: ggml-org/ccache-action@v1.2.16
          with:
            key: ubuntu-${{ matrix.ver }}-cmake-cuda-${{ matrix.cuda}}
            evict-old-files: 1d
            save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

        - name: Setup cmake
          uses: jwlawson/actions-setup-cmake@v2
          with:
            cmake-version: '3.28.x'

        - name: Build with CMake
          # TODO: Remove GGML_CUDA_CUB_3DOT2 flag once CCCL 3.2 is bundled within CTK and that CTK version is used in this project
          run: |
            cmake -S . -B build -G Ninja \
              -DLLAMA_CURL=OFF \
              -DLLAMA_OPENSSL=ON \
              -DLLAMA_FATAL_WARNINGS=ON \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CUDA_ARCHITECTURES="${{ matrix.architectures }}" \
              -DCMAKE_EXE_LINKER_FLAGS=-Wl,--allow-shlib-undefined \
              -DGGML_NATIVE=OFF \
              -DGGML_BACKEND_DL=ON \
              -DGGML_CUDA=ON \
              -DGGML_CUDA_CUB_3DOT2=ON \
              -DGGML_CUDA_FA_ALL_QUANTS=ON
            cmake --build build
            cmake --install build --config Release --prefix build/stage

  jetson-arm64:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        include:
          - ver: '36.4.0'
            cuda: '12.6'
            build: 'jp-36.4'
            architectures: '53-real;72-real;87-real'

    container: nvcr.io/nvidia/l4t-jetpack:r${{ matrix.ver }}
    steps:
        - name: Install dependencies
          env:
            DEBIAN_FRONTEND: noninteractive
          run: |
              apt update
              apt install -y cmake build-essential ninja-build libgomp1 git libcurl4-openssl-dev zip

        - name: Clone
          id: checkout
          uses: actions/checkout@v4

        - name: Fixup git checkout
          run: |
            uname -m
            git config --global --add safe.directory $(pwd)
            git rev-parse

        - name: ccache
          uses: hendrikmuhs/ccache-action@v1.2.16
          with:
            key: build-${{ matrix.ver }}-cmake-cuda-${{ matrix.cuda}}-${{ matrix.build }}
            evict-old-files: 1d

        - name: Setup cmake
          uses: whitty/actions-setup-cmake@linux-aarch64
          with:
            cmake-version: '3.28.x'

        - name: Build with CMake
          run: |
            cmake -S . -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CUDA_ARCHITECTURES="${{ matrix.architectures }}" \
              -DCMAKE_EXE_LINKER_FLAGS=-Wl,--allow-shlib-undefined \
              -DLLAMA_FATAL_WARNINGS=ON \
              -DGGML_NATIVE=OFF \
              -DGGML_BACKEND_DL=ON \
              -DGGML_CUDA_FA_ALL_QUANTS=ON \
              -DGGML_CUDA=ON
            cmake --build build
            cmake --install build --config Release --prefix build/stage

  ubuntu-cmake-cuda-arm:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        include:
          - ver: 'ubuntu24.04'
            cuda: '12.8.1'
            build: '24.04-arm64'
            architectures: '53-real;72-real;87-real'
          - ver: 'ubuntu22.04'
            cuda: '12.8.1'
            build: '22.04-arm64'
            architectures: '53-real;72-real;87-real'

    container: nvidia/cuda:${{ matrix.cuda }}-devel-${{ matrix.ver }}

    steps:
        - name: Install dependencies
          env:
            DEBIAN_FRONTEND: noninteractive
          run: |
              apt update
              apt install -y cmake build-essential ninja-build libgomp1 git libcurl4-openssl-dev zip

        - name: Clone
          id: checkout
          uses: actions/checkout@v6

        - name: Fixup git checkout
          run: |
            uname -m
            git config --global --add safe.directory $(pwd)
            git rev-parse

        - name: ccache
          uses: hendrikmuhs/ccache-action@v1.2.16
          with:
            key: ubuntu-${{ matrix.ver }}-cmake-cuda-${{ matrix.cuda}}
            evict-old-files: 1d

        - name: Setup cmake
          uses: whitty/actions-setup-cmake@linux-aarch64
          with:
            cmake-version: '3.28.x'

        - name: Build with CMake
          run: |
            cmake -S . -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CUDA_ARCHITECTURES="${{ matrix.architectures }}" \
              -DCMAKE_EXE_LINKER_FLAGS=-Wl,--allow-shlib-undefined \
              -DLLAMA_FATAL_WARNINGS=ON \
              -DGGML_NATIVE=OFF \
              -DGGML_BACKEND_DL=ON \
              -DGGML_CUDA_FA_ALL_QUANTS=ON \
              -DGGML_CUDA=ON
            cmake --build build
            cmake --install build --config Release --prefix build/stage

  windows-2022-cmake-cuda:
    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - cuda: '12.8'
            architectures: '50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90-real;120-real'

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Install ccache
        uses: ggml-org/ccache-action@v1.2.16
        with:
          key: windows-cuda-${{ matrix.cuda }}
          variant: ccache
          evict-old-files: 1d
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Install Cuda Toolkit
        uses: ./.github/actions/windows-setup-cuda
        with:
          cuda_version: ${{ matrix.cuda }}

      - name: Install Ninja
        id: install_ninja
        run: |
          choco install ninja

      - name: Build
        id: cmake_build
        shell: cmd
        # TODO: Remove GGML_CUDA_CUB_3DOT2 flag once CCCL 3.2 is bundled within CTK and that CTK version is used in this project
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -S . -B build -G "Ninja Multi-Config" ^
            -DLLAMA_BUILD_SERVER=ON ^
            -DLLAMA_CURL=OFF ^
            -DLLAMA_BUILD_BORINGSSL=ON ^
            -DCMAKE_CUDA_ARCHITECTURES=${{ matrix.architectures }} ^
            -DGGML_NATIVE=OFF ^
            -DGGML_BACKEND_DL=ON ^
            -DGGML_CPU_ALL_VARIANTS=ON ^
            -DGGML_CUDA=ON ^
            -DGGML_CUDA_FA_ALL_QUANTS=ON ^
            -DGGML_RPC=ON ^
            -DGGML_CUDA_CUB_3DOT2=ON
          set /A NINJA_JOBS=%NUMBER_OF_PROCESSORS%-1
          cmake --build build --config Release -j %NINJA_JOBS% -t ggml
          cmake --build build --config Release
          cmake --install build --config Release --prefix build/stage
